<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cc.bamboo</groupId>
        <artifactId>rwa</artifactId>
        <version>${revision}</version>
    </parent>
    <modules>
        <module>rwa-module-user-api</module>
        <module>rwa-module-user-biz</module>
    </modules>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>rwa-module-user</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        user 模块
    </description>

</project>